### ISSUE TITLE
is there any way to run it as headless?

### ISSUE THREAD

**Issue by leabdalla** [iammrhelo/InstagramCrawler#9]
is there any way to run it as headless?

**Comment by tzuhsial** [comment]
Nice suggestion! I'll include this in the future plan

**Comment by JakeCowton** [comment]
Could be a simple solution to this

https://stackoverflow.com/questions/7568899/does-selenium-support-headless-browser-testing

**Comment by leabdalla** [comment]
Nice hint, @JakeCowton !
It worked and I added with another some feats to Pull Request #11

**Comment by tzuhsial** [comment]
merged
